export const questions = {
  math: {
   easy: [
      { q: "2 + 2 = ?", a: ["3", "4", "5", "6"], correct: 1 },
      { q: "10 - 7 = ?", a: ["1","2","3","4"], correct: 2 },
      { q: "5 × 3 = ?", a: ["15", "10", "20", "12"], correct: 0 },
      { q: "15 ÷ 3 = ?", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "7 + 6 = ?", a: ["12", "13", "14", "15"], correct: 1 },
      { q: "9 - 4 = ?", a: ["5", "4", "6", "3"], correct: 0 },
      { q: "8 × 2 = ?", a: ["14", "16", "18", "20"], correct: 1 },
      { q: "12 ÷ 4 = ?", a: ["2", "3", "4", "5"], correct: 1 },
      { q: "6 + 5 = ?", a: ["10", "11", "12", "13"], correct: 1 },
      { q: "3 × 7 = ?", a: ["20", "21", "19", "18"], correct: 1 },
      { q: "10 + 9 = ?", a: ["18", "19", "20", "21"], correct: 1 },
      { q: "14 - 6 = ?", a: ["7", "8", "9", "10"], correct: 1 },
      { q: "2 × 9 = ?", a: ["17", "18", "19", "16"], correct: 1 },
      { q: "8 ÷ 2 = ?", a: ["2", "3", "4", "5"], correct: 2 },
      { q: "11 + 4 = ?", a: ["14", "15", "16", "17"], correct: 1 },
      { q: "15 - 7 = ?", a: ["7", "8", "9", "10"], correct: 1 },
      { q: "5 × 5 = ?", a: ["20", "25", "30", "35"], correct: 1 },
      { q: "20 ÷ 5 = ?", a: ["3", "4", "5", "6"], correct: 2 },
      { q: "7 + 8 = ?", a: ["14", "15", "16", "17"], correct: 1 },
      { q: "9 × 2 = ?", a: ["16", "18", "20", "19"], correct: 1 },
      { q: "13 - 5 = ?", a: ["7", "8", "9", "10"], correct: 1 },
      { q: "6 × 4 = ?", a: ["20", "22", "24", "26"], correct: 2 },
      { q: "18 ÷ 3 = ?", a: ["5", "6", "7", "8"], correct: 1 },
      { q: "4 + 9 = ?", a: ["12", "13", "14", "15"], correct: 1 },
      { q: "7 × 3 = ?", a: ["20", "21", "22", "23"], correct: 1 },
      { q: "16 - 8 = ?", a: ["7", "8", "9", "10"], correct: 1 },
      { q: "3 × 6 = ?", a: ["17", "18", "19", "20"], correct: 1 },
      { q: "12 + 5 = ?", a: ["16", "17", "18", "19"], correct: 1 },
      { q: "14 ÷ 2 = ?", a: ["6", "7", "8", "9"], correct: 1 },
      { q: "9 + 8 = ?", a: ["16", "17", "18", "19"], correct: 1 },
      { q: "5 × 4 = ?", a: ["18", "19", "20", "21"], correct: 2 },
      { q: "11 - 6 = ?", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "7 + 9 = ?", a: ["15", "16", "17", "18"], correct: 2 },
      { q: "8 × 3 = ?", a: ["22", "23", "24", "25"], correct: 2 },
      { q: "15 - 8 = ?", a: ["6", "7", "8", "9"], correct: 1 },
      { q: "6 × 5 = ?", a: ["28", "29", "30", "31"], correct: 2 },
      { q: "18 ÷ 6 = ?", a: ["2", "3", "4", "5"], correct: 1 },
      { q: "9 + 7 = ?", a: ["15", "16", "17", "18"], correct: 1 },
      { q: "3 × 8 = ?", a: ["23", "24", "25", "26"], correct: 1 },
      { q: "12 - 5 = ?", a: ["6", "7", "8", "9"], correct: 2 },
      { q: "5 + 13 = ?", a: ["17", "18", "19", "20"], correct: 2 },
      { q: "4 × 7 = ?", a: ["27", "28", "29", "30"], correct: 1 },
      { q: "10 ÷ 2 = ?", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "11 + 6 = ?", a: ["16", "17", "18", "19"], correct: 1 },
      { q: "8 - 3 = ?", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "9 × 5 = ?", a: ["44", "45", "46", "47"], correct: 1 },
      { q: "20 - 9 = ?", a: ["10", "11", "12", "13"], correct: 1 },
      { q: "6 + 12 = ?", a: ["17", "18", "19", "20"], correct: 1 },
      { q: "7 × 4 = ?", a: ["26", "27", "28", "29"], correct: 2 },
      { q: "15 ÷ 3 = ?", a: ["4", "5", "6", "7"], correct: 1 }
    ],
medium: [
      { q: "Solve for x: 2x + 5 = 13", a: ["3", "4", "5", "6"], correct: 1 },
      { q: "If x = 4, what is 3x - 2?", a: ["10", "11", "12", "13"], correct: 2 },
      { q: "Area of rectangle with length 5 and width 7?", a: ["30", "35", "40", "45"], correct: 1 },
      { q: "What is 15% of 200?", a: ["25", "30", "35", "40"], correct: 3 },
      { q: "Solve: 5x - 7 = 18", a: ["4", "5", "6", "7"], correct: 3 },
      { q: "The sum of two consecutive numbers is 19. What are the numbers?", a: ["9 & 10", "8 & 11", "10 & 9", "7 & 12"], correct: 0 },
      { q: "A triangle has base 10 and height 5. What is its area?", a: ["20", "25", "30", "15"], correct: 1 },
      { q: "Solve for y: 3y + 4 = 19", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "What is the perimeter of a square with side 6?", a: ["18", "22", "24", "30"], correct: 2 },
      { q: "If 2x = 10, then x = ?", a: ["4", "5", "6", "8"], correct: 1 },
      { q: "Solve: 7 + 3x = 19", a: ["3", "4", "5", "6"], correct: 2 },
      { q: "A rectangle has length 8 and width 3. Find the area.", a: ["22", "24", "25", "26"], correct: 1 },
      { q: "The product of a number and 6 is 42. Find the number.", a: ["6", "7", "8", "9"], correct: 1 },
      { q: "Solve for x: x/5 = 7", a: ["30", "33", "35", "37"], correct: 2 },
      { q: "What is 40% of 150?", a: ["50", "55", "60", "65"], correct: 2 },
      { q: "A triangle has sides 5, 12, and 13. Is it a right triangle?", a: ["Yes", "No", "Cannot tell", "Maybe"], correct: 0 },
      { q: "If x + 3 = 9, then x = ?", a: ["5", "6", "7", "8"], correct: 1 },
      { q: "Solve: 2x + 7 = 15", a: ["3", "4", "5", "6"], correct: 1 },
      { q: "A rectangle has perimeter 20 and length 6. Find width.", a: ["4", "5", "6", "7"], correct: 0 },
      { q: "If 3x = 18, what is x?", a: ["5", "6", "7", "8"], correct: 1 },
      { q: "What is 25% of 80?", a: ["15", "20", "25", "30"], correct: 1 },
      { q: "Solve for x: 4x - 5 = 11", a: ["3", "4", "5", "6"], correct: 2 },
      { q: "Area of a triangle with base 14 and height 3?", a: ["18", "19", "21", "22"], correct: 2 },
      { q: "If 2x + 3 = 13, x = ?", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "The sum of three consecutive numbers is 36. Find the numbers.", a: ["11,12,13", "12,13,14", "10,11,12", "9,10,11"], correct: 1 },
      { q: "What is the perimeter of a rectangle with length 10 and width 4?", a: ["28", "30", "32", "34"], correct: 0 },
      { q: "Solve: 5x + 2 = 17", a: ["3", "4", "5", "6"], correct: 2 },
      { q: "A square has area 49. Find its side.", a: ["6", "7", "8", "9"], correct: 1 },
      { q: "If x - 4 = 10, x = ?", a: ["12", "13", "14", "15"], correct: 2 },
      { q: "Solve: 6 + 2x = 14", a: ["3", "4", "5", "6"], correct: 1 },
      { q: "What is 30% of 90?", a: ["25", "26", "27", "28"], correct: 2 },
      { q: "A triangle has sides 6, 8, 10. Area?", a: ["24", "25", "26", "30"], correct: 0 },
      { q: "Solve for y: 5y - 10 = 15", a: ["4", "5", "6", "7"], correct: 2 },
      { q: "Perimeter of square with side 9?", a: ["36", "34", "32", "38"], correct: 0 },
      { q: "If x/2 + 3 = 7, x = ?", a: ["6", "7", "8", "9"], correct: 2 },
      { q: "Solve: 3x + 2 = 11", a: ["2", "3", "4", "5"], correct: 2 },
      { q: "Area of rectangle with length 12, width 5?", a: ["55", "60", "65", "70"], correct: 1 },
      { q: "If 7x = 35, x = ?", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "What is 20% of 50?", a: ["8", "9", "10", "11"], correct: 2 },
      { q: "Solve: 8x - 4 = 12", a: ["1", "2", "3", "4"], correct: 3 },
      { q: "A triangle has base 10, height 6. Area?", a: ["25", "28", "30", "32"], correct: 2 },
      { q: "If 3x + 4 = 19, x = ?", a: ["4", "5", "6", "7"], correct: 2 },
      { q: "Perimeter of rectangle length 7, width 3?", a: ["18", "19", "20", "21"], correct: 2 },
      { q: "Solve for x: x/4 + 3 = 7", a: ["14", "15", "16", "17"], correct: 2 },
      { q: "What is 50% of 80?", a: ["35", "40", "45", "50"], correct: 1 },
      { q: "A triangle sides 9,12,15. Area?", a: ["54", "56", "58", "60"], correct: 0 },
      { q: "Solve: 2x + 7 = 19", a: ["5", "6", "7", "8"], correct: 3 },
      { q: "Perimeter of square side 8?", a: ["30", "32", "34", "36"], correct: 1 },
      { q: "If 5x = 25, x = ?", a: ["4", "5", "6", "7"], correct: 1 },
      { q: "What is 10% of 250?", a: ["20", "25", "30", "35"], correct: 1 },
      { q: "Solve for y: 4y - 8 = 12", a: ["4", "5", "6", "7"], correct: 2 },
      { q: "Area of rectangle length 9, width 4?", a: ["34", "35", "36", "37"], correct: 2 },
      { q: "If x + 5 = 13, x = ?", a: ["7", "8", "9", "10"], correct: 1 },
      { q: "Solve: 6x + 3 = 27", a: ["3", "4", "5", "6"], correct: 2 },
      { q: "What is 35% of 200?", a: ["65", "70", "75", "80"], correct: 1},
    ],
  hard: [
      { q: "Solve for x: 2x² - 8x + 6 = 0", a: ["1 or 3", "2 or 3", "1 or 2", "2 only"], correct: 0 },
      { q: "If f(x) = 3x + 2, what is f(5)?", a: ["15", "16", "17", "18"], correct: 2 },
      { q: "A triangle has sides 5, 12, 13. What is its area?", a: ["30", "60", "36", "50"], correct: 0 },
      { q: "Solve: 4(x-1)² = 16", a: ["1,5", "2,6", "0,4", "3,7"], correct: 2 },
      { q: "If 2^x = 16, what is x?", a: ["2", "3", "4", "5"], correct: 2 },
      { q: "Simplify: (x²y³)(2xy²)", a: ["2x³y⁵", "2x³y⁶", "2x²y⁵", "2x³y⁴"], correct: 0 },
      { q: "Solve for x: x² - 9x + 20 = 0", a: ["4 or 5", "5 or 4", "4 or 6", "5 or 6"], correct: 3 },
      { q: "If y = 2x + 3 and y = 7, find x.", a: ["1", "2", "3", "4"], correct: 1 },
      { q: "Factor: x² - 16", a: ["(x-4)(x+4)", "(x-8)(x+2)", "(x-2)(x+8)", "(x-1)(x+16)"], correct: 0 },
      { q: "Simplify: (3x²y)(4xy³)", a: ["12x³y⁴", "12x³y³", "7x³y⁴", "12x²y³"], correct: 0 },
      { q: "Solve for x: x² + 6x + 9 = 0", a: ["-3", "3", "±3", "0"], correct: 0 },
      { q: "If f(x) = x² - 2x + 1, find f(3).", a: ["4", "3", "2", "1"], correct: 0 },
      { q: "Simplify: (2x²y⁻¹)(-3xy³)", a: ["-6x³y²", "-6x³y³", "-6x²y²", "-6x²y³"], correct: 0 },
      { q: "Solve for x: x² - 4x - 5 = 0", a: ["5, -1", "1, -5", "5, 1", "-5, -1"], correct: 0 },
      { q: "A right triangle has legs 9 and 12. Find the hypotenuse.", a: ["15", "16", "17", "18"], correct: 0 },
      { q: "Simplify: (x² + 2x + 1)/(x+1)", a: ["x+1", "x+2", "x²+1", "x"], correct: 0 },
      { q: "Solve: 3x² - 12 = 0", a: ["±2", "±√4", "±√3", "±√2"], correct: 0 },
      { q: "Factor: x² + 5x + 6", a: ["(x+2)(x+3)", "(x+1)(x+6)", "(x+3)(x+2)", "(x+6)(x+1)"], correct: 0 },
      { q: "Solve for x: 5x² - 20x = 0", a: ["0,4", "0,5", "4,5", "0, -4"], correct: 0 },
      { q: "If 2x + 3y = 12 and x = 3, find y.", a: ["1", "2", "3", "4"], correct: 1 },
      { q: "Simplify: (x³y²)/(x y)", a: ["x²y", "x³y³", "x²y²", "x y"], correct: 0 },
      { q: "Solve: x² - x - 6 = 0", a: ["3 or -2", "2 or -3", "1 or -6", "6 or -1"], correct: 0 },
      { q: "The sum of squares: 3² + 4² = ?", a: ["24", "25", "26", "27"], correct: 1 },
      { q: "Simplify: (2x³y²)²", a: ["4x⁶y⁴", "4x⁵y⁴", "2x⁶y²", "4x⁶y²"], correct: 0 },
      { q: "Solve for x: x² + 7x + 10 = 0", a: ["-5 or -2", "-2 or -5", "2 or 5", "5 or 2"], correct: 0 },
      { q: "If f(x) = 2x² - 3, find f(2).", a: ["5", "4", "3", "6"], correct: 0 },
      { q: "Factor: x² - 5x + 6", a: ["(x-2)(x-3)", "(x-1)(x-6)", "(x-3)(x-2)", "(x-6)(x-1)"], correct: 0 },
      { q: "Solve: 2x² - 8x = 0", a: ["0,4", "0,2", "2,4", "0,-4"], correct: 0 },
      { q: "Simplify: (x²y³)(x³y²)", a: ["x⁵y⁵", "x⁶y⁶", "x⁴y⁴", "x⁵y⁶"], correct: 0 },
      { q: "Solve for x: x² - 9 = 0", a: ["±3", "3", "-3", "0"], correct: 0 },
      { q: "Hypotenuse of right triangle legs 8 and 15?", a: ["17", "16", "18", "19"], correct: 0 },
      { q: "Simplify: (x² - 9)/(x - 3)", a: ["x+3", "x-3", "x²+3", "x"], correct: 0 },
      { q: "Solve: 4x² - 12x + 9 = 0", a: ["3/2", "2", "1", "3"], correct: 0 },
      { q: "Factor: x² + 6x + 8", a: ["(x+2)(x+4)", "(x+1)(x+8)", "(x+4)(x+2)", "(x+8)(x+1)"], correct: 0 },
      { q: "Solve for x: x² + 4x - 5 = 0", a: ["1 or -5", "-1 or 5", "5 or -1", "-5 or 1"], correct: 0 },
      { q: "If 3x + 2y = 18 and y = 4, find x.", a: ["2", "3", "4", "5"], correct: 1 },
      { q: "Simplify: (x³y⁴)/(x²y)", a: ["x y³", "x²y³", "x y²", "x²y²"], correct: 0 },
      { q: "Solve: 5x² - 20 = 0", a: ["±2", "±√4", "±√5", "±√20"], correct: 0 },
      { q: "Triangle with sides 7,24,25. Area?", a: ["84", "85", "86", "87"], correct: 0 },
      { q: "Factor: x² - 10x + 25", a: ["(x-5)²", "(x-25)(x+1)", "(x-1)(x-25)", "(x-5)(x+5)"], correct: 0 },
      { q: "Solve for x: 2x² - 18 = 0", a: ["3", "-3", "±3", "±9"], correct: 2 },
      { q: "Simplify: (2x²y)(3xy²)", a: ["6x³y³", "5x³y³", "6x²y³", "6x³y²"], correct: 0 },
      { q: "Solve: x² + x - 6 = 0", a: ["2 or -3", "-2 or 3", "3 or -2", "-3 or 2"], correct: 0 },
      { q: "Hypotenuse of triangle legs 12 and 5?", a: ["13", "14", "15", "16"], correct: 0 },
      { q: "Simplify: (x² - 4)/(x-2)", a: ["x+2", "x-2", "x²+2", "x"], correct: 0 },
      { q: "Solve for x: x² - 2x - 8 = 0", a: ["4 or -2", "-4 or 2", "2 or -4", "-2 or 4"], correct: 0 },
      { q: "Factor: x² - 7x + 12", a: ["(x-3)(x-4)", "(x-2)(x-6)", "(x-4)(x-3)", "(x-6)(x-2)"], correct: 0 },
      { q: "Solve: 3x² - 27 = 0", a: ["±3", "±√9", "±√3", "±√27"], correct: 0 },
      { q: "Simplify: (x³y²)²", a: ["x⁶y⁴", "x⁵y⁴", "x⁶y³", "x³y⁴"], correct: 0 },
      { q: "Solve for x: x² - 5x + 6 = 0", a: ["2 or 3", "3 or 2", "1 or 6", "6 or 1"], correct: 0 }
    ]
  },
  english: {
 easy: [
    { q: "Choose the correct word: Their/There going to the store.", a: ["Their", "There", "They're", "The're"], correct: 2 },
    { q: "Select the correct spelling:", a: ["Accomodate", "Accommodate", "Acommodate", "Acomodate"], correct: 1 },
    { q: "Pick the right word: Its/It's raining outside.", a: ["Its", "It's", "Its'", "It is'"], correct: 1 },
    { q: "Choose the correct word: To/Too/Two many people came.", a: ["To", "Too", "Two", "Tooo"], correct: 1 },
    { q: "Select the correct sentence:", a: ["She don't like it.", "She doesn't like it.", "She not likes it.", "She doesn't likes it."], correct: 1 },
    { q: "Choose the best synonym for 'happy':", a: ["Sad", "Joyful", "Angry", "Tired"], correct: 1 },
    { q: "Pick the correct word: Affect/Effect of the storm was severe.", a: ["Affect", "Effect", "Affective", "Affected"], correct: 1 },
    { q: "Select the correct sentence:", a: ["I have went there.", "I have gone there.", "I has gone there.", "I go there."], correct: 1 },
    { q: "Choose the correct word: They're/Their going on vacation.", a: ["They're", "Their", "There", "The're"], correct: 0 },
    { q: "Pick the correct word: He did good/well on the test.", a: ["Good", "Well", "Welled", "Goods"], correct: 1 },
    { q: "Select the correct form: She ___ (run) every morning.", a: ["run", "runs", "ran", "running"], correct: 1 },
    { q: "Choose the best antonym for 'big':", a: ["Large", "Huge", "Small", "Giant"], correct: 2 },
    { q: "Select the correct word: Who/Whom did you see?", a: ["Who", "Whom", "Who's", "Whose"], correct: 1 },
    { q: "Choose the correct sentence:", a: ["Me and him went.", "Him and I went.", "He and I went.", "Him and me went."], correct: 2 },
    { q: "Pick the correct word: Accept/Except the invitation.", a: ["Accept", "Except", "Acccept", "Excpect"], correct: 0 },
    { q: "Select the correct word: I could of/have done it.", a: ["of", "have", "has", "had"], correct: 1 },
    { q: "Choose the best synonym for 'fast':", a: ["Quick", "Slow", "Lazy", "Late"], correct: 0 },
    { q: "Pick the correct word: Their/There book is missing.", a: ["Their", "There", "They're", "The're"], correct: 0 },
    { q: "Select the correct word: I should of/have studied.", a: ["of", "have", "had", "has"], correct: 1 },
    { q: "Choose the correct sentence:", a: ["Its a nice day.", "It's a nice day.", "Its' a nice day.", "Its is a nice day."], correct: 1 },
    { q: "Pick the correct word: Your/You're amazing.", a: ["Your", "You're", "Yore", "You are'"], correct: 1 },
    { q: "Select the correct word: Their/There/They're friends.", a: ["Their", "There", "They're", "Thier"], correct: 0 },
    { q: "Choose the best synonym for 'angry':", a: ["Mad", "Glad", "Sad", "Tired"], correct: 0 },
    { q: "Pick the correct word: Who's/Whose bag is this?", a: ["Who's", "Whose", "Whos", "Whose's"], correct: 1 },
    { q: "Select the correct sentence:", a: ["He don't know.", "He doesn't know.", "He not know.", "He isn't knows."], correct: 1 },
    { q: "Choose the correct word: Compliment/Complement her work.", a: ["Compliment", "Complement", "Complemant", "Complimant"], correct: 0 },
    { q: "Pick the correct word: I ___ (go) to the park yesterday.", a: ["go", "went", "gone", "going"], correct: 1 },
    { q: "Select the correct word: There/Their going to the market.", a: ["There", "Their", "They're", "Thier"], correct: 2 },
    { q: "Choose the correct sentence:", a: ["She don't like pizza.", "She doesn't likes pizza.", "She doesn't like pizza.", "She not like pizza."], correct: 2 },
    { q: "Pick the correct word: Affect/Effect of the medicine.", a: ["Affect", "Effect", "Afected", "Effected"], correct: 1 },
    { q: "Select the best synonym for 'small':", a: ["Tiny", "Large", "Huge", "Gigantic"], correct: 0 },
    { q: "Choose the correct word: Its/It's been raining.", a: ["Its", "It's", "Its'", "It is'"], correct: 1 },
    { q: "Pick the correct word: To/Too/Two much sugar.", a: ["To", "Too", "Two", "Tooo"], correct: 1 },
    { q: "Select the correct sentence:", a: ["I have ate.", "I have eaten.", "I has eaten.", "I had ate."], correct: 1 },
    { q: "Choose the best antonym for 'happy':", a: ["Sad", "Joyful", "Glad", "Excited"], correct: 0 },
    { q: "Pick the correct word: Who/Whom should I call?", a: ["Who", "Whom", "Who's", "Whose"], correct: 1 },
    { q: "Select the correct word: He did good/well at the game.", a: ["Good", "Well", "Goodly", "Welled"], correct: 1 },
    { q: "Choose the correct sentence:", a: ["Them are coming.", "They are coming.", "Those are coming.", "Them is coming."], correct: 1 },
    { q: "Pick the correct word: Your/You're responsible.", a: ["Your", "You're", "Yore", "You are'"], correct: 1 },
    { q: "Select the correct word: Their/There car is fast.", a: ["Their", "There", "They're", "Thier"], correct: 0 },
    { q: "Choose the best synonym for 'easy':", a: ["Simple", "Difficult", "Hard", "Tough"], correct: 0 },
    { q: "Pick the correct word: It's/Its time to go.", a: ["It's", "Its", "Its'", "It is'"], correct: 0 },
    { q: "Select the correct sentence:", a: ["He don't know the answer.", "He doesn't know the answer.", "He not knows the answer.", "He doesn't knows the answer."], correct: 1 },
    { q: "Choose the correct word: Complement/Compliment the team.", a: ["Complement", "Compliment", "Complemant", "Complimant"], correct: 1 },
    { q: "Pick the correct word: I should of/have told you.", a: ["of", "have", "has", "had"], correct: 1 },
    { q: "Select the best antonym for 'fast':", a: ["Quick", "Slow", "Rapid", "Speedy"], correct: 1 },
    { q: "Choose the correct word: Who's/Whose notebook is this?", a: ["Who's", "Whose", "Whos", "Who"], correct: 1 },
    { q: "Pick the correct sentence:", a: ["I ain't done it.", "I haven't done it.", "I has not done it.", "I not done it."], correct: 1 }
  ],
  medium: [
    { q: "Choose the best word to complete: Despite the rain, the picnic went on ___.", a: ["successfully", "successful", "success", "succession"], correct: 0 },
    { q: "Select the correct word: She was ___ to finish the project on time.", a: ["determined", "determine", "determines", "determination"], correct: 0 },
    { q: "Pick the best synonym for 'ambiguous':", a: ["clear", "vague", "obvious", "evident"], correct: 1 },
    { q: "Choose the correct sentence:", a: ["He is more smarter than his brother.", "He is smarter than his brother.", "He is smart than his brother.", "He is the most smarter than his brother."], correct: 1 },
    { q: "Select the correct word: The committee reached a ___ decision.", a: ["unanimous", "unique", "uniform", "unknown"], correct: 0 },
    { q: "Pick the correct word: Her explanation was ___ convincing.", a: ["very", "much", "too", "so"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Neither of the answers are correct.", "Neither of the answers is correct.", "Neither of the answers were correct.", "Neither of the answer is correct."], correct: 1 },
    { q: "Select the best synonym for 'meticulous':", a: ["careful", "sloppy", "lazy", "hasty"], correct: 0 },
    { q: "Pick the correct word: The scientist made a ___ discovery.", a: ["groundbreaking", "grounded", "ground", "groundedness"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["He suggested to go early.", "He suggested going early.", "He suggested go early.", "He suggested gone early."], correct: 1 },
    { q: "Select the correct word: Her speech was ___ inspiring.", a: ["truly", "true", "truth", "trust"], correct: 0 },
    { q: "Pick the best antonym for 'artificial':", a: ["synthetic", "natural", "man-made", "fabricated"], correct: 1 },
    { q: "Choose the correct sentence:", a: ["If I was you, I would apologize.", "If I were you, I would apologize.", "If I am you, I would apologize.", "If I be you, I would apologize."], correct: 1 },
    { q: "Select the correct word: He is known for his ___ generosity.", a: ["exceptional", "except", "excessive", "exemplary"], correct: 0 },
    { q: "Pick the correct word: The new policy will ___ all employees.", a: ["affect", "effect", "affects", "effects"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["She hardly ever goes to the gym.", "She ever hardly goes to the gym.", "She goes hardly ever to the gym.", "Hardly she ever goes to the gym."], correct: 0 },
    { q: "Select the best synonym for 'diligent':", a: ["lazy", "hardworking", "careless", "neglectful"], correct: 1 },
    { q: "Pick the correct word: His attitude was ___ the cause of the problem.", a: ["indeed", "likely", "probably", "directly"], correct: 3 },
    { q: "Choose the correct sentence:", a: ["He is taller then I am.", "He is taller than I am.", "He is taller as I am.", "He is taller like I am."], correct: 1 },
    { q: "Select the correct word: The company plans to ___ new policies.", a: ["implement", "imply", "improve", "import"], correct: 0 },
    { q: "Pick the best antonym for 'scarce':", a: ["rare", "abundant", "limited", "few"], correct: 1 },
    { q: "Choose the correct sentence:", a: ["Each of the players have a role.", "Each of the players has a role.", "Each of the player has a role.", "Each of the players having a role."], correct: 1 },
    { q: "Select the correct word: He completed the task ___ than expected.", a: ["faster", "fastest", "fast", "more fast"], correct: 0 },
    { q: "Pick the correct word: The professor's lecture was ___ engaging.", a: ["highly", "high", "hight", "highest"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["If she would have studied, she would pass.", "If she had studied, she would have passed.", "If she studied, she would have passed.", "If she would studied, she would pass."], correct: 1 },
    { q: "Select the best synonym for 'obstinate':", a: ["stubborn", "flexible", "compliant", "yielding"], correct: 0 },
    { q: "Pick the correct word: The CEO emphasized ___ importance of ethics.", a: ["the", "a", "an", "that"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["He did not only finish the work but also helped others.", "He not only finished the work but also helped others.", "He did not finish the work but also helped others.", "He not finished the work but also helped others."], correct: 1 },
    { q: "Select the correct word: The painting was ___ beautiful.", a: ["absolutely", "absolute", "absolutly", "absoluteley"], correct: 0 },
    { q: "Pick the correct word: Their/There/They're planning a trip.", a: ["Their", "There", "They're", "Thier"], correct: 2 },
    { q: "Choose the correct sentence:", a: ["He is one of those students who studies diligently.", "He is one of those students who study diligently.", "He is one of those students who studying diligently.", "He is one of those students who studied diligently."], correct: 1 },
    { q: "Select the best antonym for 'opaque':", a: ["clear", "cloudy", "dark", "murky"], correct: 0 },
    { q: "Pick the correct word: She speaks ___ than anyone else.", a: ["more clearly", "most clearly", "clearest", "clearer"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["I have never seen something so beautiful.", "I have never saw something so beautiful.", "I never seen something so beautiful.", "I never saw something so beautiful."], correct: 0 },
    { q: "Select the correct word: He is known for his ___ honesty.", a: ["unquestionable", "questionable", "doubtful", "doubtless"], correct: 0 },
    { q: "Pick the best synonym for 'eloquent':", a: ["articulate", "inarticulate", "tongue-tied", "mute"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Neither option seems appealing.", "Neither option seem appealing.", "Neither options seems appealing.", "Neither options seem appealing."], correct: 0 },
    { q: "Select the correct word: She worked ___ than expected.", a: ["harder", "hardest", "more hard", "hard"], correct: 0 },
    { q: "Pick the correct word: The ___ of the novel was thrilling.", a: ["climax", "climactic", "climaxes", "climbing"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["He insisted that she go to the meeting.", "He insisted that she goes to the meeting.", "He insisted she going to the meeting.", "He insisted that she went to the meeting."], correct: 0 },
    { q: "Select the correct word: This solution is ___ effective.", a: ["highly", "high", "higher", "highest"], correct: 0 },
    { q: "Pick the best antonym for 'transparent':", a: ["opaque", "clear", "visible", "lucid"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["If I were you, I would accept the offer.", "If I was you, I would accept the offer.", "If I am you, I would accept the offer.", "If I be you, I would accept the offer."], correct: 0 },
    { q: "Select the correct word: The teacher explained the topic ___ clearly.", a: ["very", "much", "so", "too"], correct: 0 },
    { q: "Pick the correct word: He is ___ responsible for the project.", a: ["directly", "indirectly", "distantly", "closely"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Few students understand the concept.", "A few students understand the concept.", "Few students understands the concept.", "A few student understands the concept."], correct: 0 },
    { q: "Select the best synonym for 'resilient':", a: ["strong", "weak", "fragile", "delicate"], correct: 0 },
    { q: "Pick the correct word: They are ___ to finish on time.", a: ["likely", "unlikely", "certain", "possible"], correct: 0 }
  ],
  hard: [
    { q: "Choose the most precise word: The scientist provided a ___ analysis of the data.", a: ["meticulous", "careless", "superficial", "ambiguous"], correct: 0 },
    { q: "Select the correct sentence:", a: ["Had I known about the test, I would have studied.", "If I knew about the test, I would have studied.", "Had I knew about the test, I would have studied.", "If I had knew about the test, I would have studied."], correct: 0 },
    { q: "Pick the best synonym for 'cogent':", a: ["convincing", "weak", "unpersuasive", "trivial"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["No sooner had he arrived than the meeting started.", "No sooner he arrived than the meeting started.", "No sooner had he arrive than the meeting started.", "No sooner had he arriving than the meeting started."], correct: 0 },
    { q: "Select the best antonym for 'ephemeral':", a: ["lasting", "brief", "fleeting", "transient"], correct: 0 },
    { q: "Pick the correct word: The CEO emphasized the ___ necessity of innovation.", a: ["paramount", "minor", "negligible", "secondary"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Seldom have I witnessed such dedication.", "Seldom I have witnessed such dedication.", "Seldom have I witnessing such dedication.", "Seldom I witnessed such dedication."], correct: 0 },
    { q: "Select the best synonym for 'obfuscate':", a: ["confuse", "clarify", "explain", "illuminate"], correct: 0 },
    { q: "Pick the correct word: His argument was ___ persuasive, convincing the jury.", a: ["highly", "most", "very", "extremely"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Not only did she excel in math, but also in science.", "Not only she excelled in math, but also in science.", "Not only did she excel in math, but she excelled also in science.", "Not only she excelled in math, also in science."], correct: 0 },
    { q: "Select the correct word: The treaty was signed to ___ peace between nations.", a: ["ensure", "insure", "assure", "secure"], correct: 0 },
    { q: "Pick the best synonym for 'alacrity':", a: ["eagerness", "reluctance", "sluggishness", "hesitation"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Rarely had he felt so accomplished.", "Rarely he had felt so accomplished.", "Rarely he felt so accomplished.", "Rarely had he feeling so accomplished."], correct: 0 },
    { q: "Select the best antonym for 'loquacious':", a: ["taciturn", "verbose", "garrulous", "talkative"], correct: 0 },
    { q: "Pick the correct word: The politician’s speech was full of ___ rhetoric.", a: ["bombastic", "concise", "plain", "modest"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Scarcely had the sun risen when the birds began singing.", "Scarcely the sun had risen when the birds began singing.", "Scarcely had the sun rise when the birds began singing.", "Scarcely had the sun rising when the birds began singing."], correct: 0 },
    { q: "Select the correct word: His decision was guided by ___ judgment.", a: ["sound", "unsound", "poor", "flawed"], correct: 0 },
    { q: "Pick the best synonym for 'capricious':", a: ["fickle", "steady", "predictable", "consistent"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Hardly had she begun speaking when the phone rang.", "Hardly she had begun speaking when the phone rang.", "Hardly had she began speaking when the phone rang.", "Hardly had she begin speaking when the phone rang."], correct: 0 },
    { q: "Select the correct word: The proposal was met with ___ approval.", a: ["unanimous", "divided", "mixed", "partial"], correct: 0 },
    { q: "Pick the best antonym for 'obdurate':", a: ["yielding", "stubborn", "hard", "rigid"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Rarely do we see such talent.", "Rarely we see such talent.", "Rarely see we such talent.", "Rarely do we seeing such talent."], correct: 0 },
    { q: "Select the correct word: His work was ___ admired by his peers.", a: ["widely", "narrowly", "partially", "slightly"], correct: 0 },
    { q: "Pick the best synonym for 'esoteric':", a: ["obscure", "common", "ordinary", "popular"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Seldom does one encounter such brilliance.", "Seldom one does encounter such brilliance.", "Seldom does one encountering such brilliance.", "Seldom one encounters does such brilliance."], correct: 0 },
    { q: "Select the correct word: The hypothesis was ___ tested before acceptance.", a: ["rigorously", "lazily", "superficially", "sloppily"], correct: 0 },
    { q: "Pick the best antonym for 'placid':", a: ["turbulent", "calm", "serene", "peaceful"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Only after the meeting did he realize the mistake.", "Only after the meeting he did realize the mistake.", "Only after the meeting did he realizing the mistake.", "Only after the meeting did he realized the mistake."], correct: 0 },
    { q: "Select the correct word: The artist’s work was ___ innovative.", a: ["remarkably", "barely", "moderately", "slightly"], correct: 0 },
    { q: "Pick the best synonym for 'mollify':", a: ["appease", "anger", "provoke", "inflame"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["No sooner had they arrived than the concert began.", "No sooner they had arrived than the concert began.", "No sooner had they arrive than the concert began.", "No sooner they arrived had the concert began."], correct: 0 },
    { q: "Select the correct word: The committee acted with ___ urgency.", a: ["prompt", "leisurely", "delayed", "slow"], correct: 0 },
    { q: "Pick the best antonym for 'gregarious':", a: ["introverted", "sociable", "friendly", "outgoing"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Rarely have we witnessed such chaos.", "Rarely we have witnessed such chaos.", "Rarely have we witnessing such chaos.", "Rarely we witnessed such chaos."], correct: 0 },
    { q: "Select the correct word: The lawyer’s argument was ___ compelling.", a: ["exceptionally", "barely", "moderately", "slightly"], correct: 0 },
    { q: "Pick the best synonym for 'obsequious':", a: ["fawning", "assertive", "dominant", "bold"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Hardly had the event started when the rain began.", "Hardly had the event start when the rain began.", "Hardly the event had started when the rain began.", "Hardly had the event starting when the rain began."], correct: 0 },
    { q: "Select the correct word: The theory was ___ validated by experiments.", a: ["thoroughly", "partially", "superficially", "haphazardly"], correct: 0 },
    { q: "Pick the best antonym for 'inimical':", a: ["friendly", "hostile", "unfriendly", "adverse"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Only when the sun rose did the birds begin singing.", "Only when the sun rose the birds begin singing.", "Only when the sun rose did the birds began singing.", "Only when the sun rose did birds begin singing."], correct: 0 },
    { q: "Select the correct word: The diplomat acted with ___ discretion.", a: ["utmost", "least", "moderate", "minimal"], correct: 0 },
    { q: "Pick the best synonym for 'pulchritude':", a: ["beauty", "ugliness", "plainness", "simplicity"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Little did he know what awaited him.", "Little he knew what awaited him.", "Little did he knew what awaited him.", "Little did he knowing what awaited him."], correct: 0 },
    { q: "Select the correct word: The argument was ___ sound.", a: ["logically", "illogically", "flawed", "baseless"], correct: 0 },
    { q: "Pick the best antonym for 'sanction':", a: ["forbid", "allow", "permit", "approve"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Not until the bell rang did the students leave.", "Not until the bell rang the students did leave.", "Not until the bell rang did students leave.", "Not until the bell rang students did leave."], correct: 0 },
    { q: "Select the correct word: His interpretation was ___ insightful.", a: ["highly", "barely", "somewhat", "slightly"], correct: 0 },
    { q: "Pick the best synonym for 'recalcitrant':", a: ["uncooperative", "obedient", "submissive", "compliant"], correct: 0 },
    { q: "Choose the correct sentence:", a: ["Scarcely had he finished when the call came.", "Scarcely he had finished when the call came.", "Scarcely had he finish when the call came.", "Scarcely he finished had when the call came."], correct: 0 }
]
  }
};